language: go
go:
  - 1.11.x
branches:
  only:
  - master
script:
  - make build
sudo: false
deploy:
  provider: releases
  api_key:
    secure: TloLHm3BTcYFpnygMGR61/9HcJYiUvJSDxfEddrIv89IuDtkRJwXbfkDLHTteL43mf6Y9ig8V5Ihn6pd24PWeyPv2Q2UJDTgQ8sTiqu5/KvUpRnDfXn5Hji+KT/ZJycw0MH7aW4gG8RfZW/4VdtUT5WjRdHvR3cUviMp1Os/P5QhghyiERnYZAjLWdtOgEh1+UGHrCtmdg7oPNTBIA84AbhFThjkEfvLCxn/umQscs/jlS/xqTN3nMWTVeL5WD3/7EJH3p/ibwzxQgEqGTdnLZ5MzMiNEo6x+i81Eyp9asFz9SkrcDOA7k2Q+2jHq0DTtNsPObfuIGQydZTFDVizHzYkR8D0KmB59nST2acRs/DfQq8gbz7UC09BFq1cldFCaLccZxfRMyVhhvdFJgwQbxfwAZsLsouKRgDA0cu3+P6rfDVqkITX1ydilc7aU521yCzT1/mVIroaSV1LhAuNJIXbxRS311D63FwXtRfpy32yOUS3U2a6AjabFDAPxLaoG1tcWmbG6lH1BkYQcqDq3jXzFZCL+1VraYl5q/JXlJQHswl4M6kvin8J/n5MzCIC8aTPwreDpL+L4zEYYN2M6i4i0fz+E01Rhj/xABvSwvLST2P+Q6GJkOh9UjZkDhTJB9V/FN6OQm/a/zpWD5yj1hOJtQvYETUzHHl3R5DI3dQ=
  file: netopticon
  on:
    repo: criteo/netopticon
  skip_cleanup: true
